export const QUESTIONS = [
  "1. Why did you start coaching—and what pain did you have to overcome to get here?",
  "2. Who do you serve and what pain do they feel in their body, mind, and life?",
  "3. What do you hate about the fitness industry right now?",
  "4. What values do you live and coach by, no exceptions?",
  "5. What do clients say about your coaching style that surprises you?",
  "6. What rules do your clients have to follow to succeed?",
  "7. What are the biggest lies being pushed around fat loss or muscle gain?",
  "8. How do you blend mindset with macros or movement?",
  "9. When do you ditch tracking—and when is it non-negotiable?",
  "10. How do you coach someone through chaos—travel, stress, burnout?",
  "11. Walk us through a perfect transformation arc—Day 1 to Day 90.",
  "12. What's your #1 system for keeping clients consistent long-term?",
  "13. What metrics matter to you beyond the scale?",
  "14. What do you do when a client ghosts or stops checking in?",
  "15. What's your plateau protocol—what do you audit and in what order?",
  "16. Break down your transformation method from first call to last win.",
  "17. How do you build meals/macros that work in the real world?",
  "18. How do you change training for fat loss vs. performance vs. hormone health?",
  "19. What's your full lens on hormone repair, gut issues, and metabolic recovery?",
  "20. How do you coach sleep, digestion, and stress like a system—not a checklist?",
  "21. What's your coaching tone: fire, nurture, humor, savage, clinical?",
  "22. What are your top 3 go-to phrases or mantras with clients?",
  "23. How do you teach deep concepts (thyroid, cortisol, PCOS) in plain English?",
  "24. What objections do you hear all the time—and how do you flip them?",
  "25. What's your war cry when a client's slipping or doubting themselves?",
  "26. What content always pops off—and why?",
  "27. What's one controversial take you stand by that others won't say?",
  "28. What do you want strangers to feel within 3 seconds of finding your page?",
  "29. What quote or philosophy defines how you show up online and in life?",
  "30. If your AI could only coach one topic for eternity—what would it say, and how?"
];
